### ISSUE TITLE
TemplateDoesNotExist: base.html

### ISSUE THREAD

**Issue by umrashrf** [Kwpolska/django-expenses#8]
```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/homebrew/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/me/app/expenses/views/__init__.py", line 92, in index
    return render(
  File "/opt/homebrew/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/homebrew/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/homebrew/lib/python3.9/site-packages/django/template/backends/django.py", line 64, in render
    reraise(exc, self.backend)
  File "/opt/homebrew/lib/python3.9/site-packages/django/template/backends/django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
```

**Comment by Kwpolska** [comment]
You need a `base.html` template, one is not provided as an example, perhaps it should be — I’ll try to provide one somewhere.

**Comment by Kwpolska** [comment]
I added a `base.html.sample` file that should be enough for Expenses to work.
